# Generated by Django 3.0.5 on 2020-05-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0004_auto_20200520_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ohms',
            name='current',
        ),
        migrations.RemoveField(
            model_name='ohms',
            name='resistance',
        ),
        migrations.RemoveField(
            model_name='ohms',
            name='voltage',
        ),
    ]
