# Generated by Django 3.0.5 on 2020-05-21 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0006_auto_20200521_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohms',
            name='current',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ohms',
            name='resistance',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ohms',
            name='voltage',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
